ALTER TABLE P_OWNER DROP CONSTRAINT P_OWNER_EMAIL_CHECK;
ALTER TABLE P_OWNER ADD CONSTRAINT P_OWNER_EMAIL_CHECK CHECK
											(EMAIL LIKE '%@%.%' AND EMAIL LIKE '%@@%.%' AND EMAIL NOT LIKE '@.');


ALTER TABLE P_HOUSE DROP CONSTRAINT P_HOUSE_ACREAGE_CHECK;
ALTER TABLE P_OWNER ADD CONSTRAINT P_HOUSE_ACREAGE_CHECK CHECK
											(ACREAGE >= 0 OR ACREAGE <= 100)
