CREATE VIEW P_PHONECONTACT_VERIFICATION_V AS
SELECT LNAME, FNAME, EMAIL, PHONE_CONTACTID, PHONENUM, PHONETYPE, LAST_DATE_VERIFIED
FROM P_OWNER, P_OWNERPHONE, P_OWNERCONTACT
WHERE LAST_DATE_VERIFIED - TRUNC(SYSDATE) > 365
ORDER BY LNAME ASC
