CREATE VIEW P_PHONECONTACT_VERIFICATION_V AS
SELECT LNAME, FNAME, EMAIL, PHONE_CONTACTID, PHONENUM, PHONETYPE, LAST_DATE_VERIFIED
FROM P_OWNER, P_OWNERPHONE, P_OWNERCONTACT
WHERE LAST_DATE_VERIFIED  < TRUNC(SYSDATE) - 365
ORDER BY LNAME;

DROP VIEW P_PHONECONTACT_VERIFICATION_V;

CREATE VIEW P_10001_STATEMENT_V AS
SELECT DISTINCT P_STATEMENTITEMS.STATEMENTID, P_STATEMENT.STATEMENTDATE, P_STATEMENT.OWNERID, P_OWNER.LNAME, P_OWNER.FNAME, P_PROPERTY.PROPERTYID, P_PROPERTY.STREET1, P_PROPERTY.STREET2, P_PROPERTY.CITY, P_PROPERTY.STATE, P_PROPERTY.ZIP, P_ISSUES.ISSUETYPE, P_ISSUES.OTHER
FROM P_STATEMENT, P_STATEMENTITEMS, P_OWNER, P_PROPERTY, P_ISSUES
WHERE P_STATEMENT.OWNERID = '10001' AND P_STATEMENTITEMS.STATEMENTID = '40001'
ORDER BY P_OWNER.LNAME;

DROP VIEW P_10001_STATEMENT_V;


CREATE VIEW P_ACTIONS_WAITING_STATS_V AS
SELECT COUNT(IS_ACTION_WAITING_RESPONSE) AS ACTIONS_WAITING_MORE_THAN_60,
AVG(SYSDATE - ACTIONDATE) AS AVERAGE_DAYS_WAITING,
MAX(SYSDATE - ACTIONDATE) AS MAX_DAYS_WAITING
FROM P_ACTIONS
WHERE IS_ACTION_WAITING_RESPONSE = 'Y';

DROP VIEW P_ACTIONS_WAITING_STATS_V;


CREATE VIEW P_OWNERS_AND_PROPERTIES_V AS
SELECT DISTINCT P_OWNER.OWNERID, P_OWNER.LNAME, P_OWNER.FNAME, B2.PROPERTYID, B1.PURCHASEDATE
FROM P_OWNER, P_PURCHASE B1, P_PROPERTY B2
WHERE B1.PROPERTYID = B2.PROPERTYID AND NOT EXISTS
	(SELECT *
  FROM P_PURCHASE B2
  WHERE B1.PROPERTYID = B2.PROPERTYID
  AND B1.PURCHASEDATE < B2.PURCHASEDATE)
ORDER BY P_OWNER.OWNERID;

DROP VIEW P_OWNERS_AND_PROPERTIES_V;
